#ifndef PRODUCTION_H
#define PRODUCTION_H

#include "../stack/stack.h"

typedef enum {

  PROD_NONE,

  PROD_CODE_BLOCK_EOF,

  PROD_BLOCK_LBRACE_PROG_RBRACE,

  PROD_PROG_DECL_PROG,
  PROD_PROG_EPSILON,

  PROD_DECL_VAR_DECLARATION,
  PROD_DECL_ASSIGNMENT,
  PROD_DECL_CONDITION,
  PROD_DECL_WHILE_LOOP,

  PROD_VAR_DECLARATION_TYPE_IDENTIFIER_VAR_DECLARATION_TAIL,

  PROD_VAR_DECLARATION_TAIL_SEMICOLON,
  PROD_VAR_DECLARATION_TAIL_ASSIGN_EXPR_SEMICOLON,

  PROD_ASSIGNMENT_IDENTIFIER_ASSIGN_EXPR_SEMICOLON,

  PROD_CONDITION_IF_LPAREN_EXPR_RPAREN_BLOCK_CONDITION_TAIL,

  PROD_CONDITION_TAIL_ELSE_BLOCK,
  PROD_CONDITION_TAIL_EPSILON,

  PROD_WHILE_LOOP_WHILE_LPAREN_EXPR_RPAREN_BLOCK,

  PROD_EXPR_LOGICAL_OR_EXPR,

  PROD_LOGICAL_OR_EXPR_LOGICAL_AND_EXPR_LOGICAL_OR_EXPR_TAIL,

  PROD_LOGICAL_OR_EXPR_TAIL_OR_LOGICAL_AND_EXPR_LOGICAL_OR_EXPR_TAIL,
  PROD_LOGICAL_OR_EXPR_TAIL_EPSILON,

  PROD_LOGICAL_AND_EXPR_EQUALITY_EXPR_LOGICAL_AND_EXPR_TAIL,

  PROD_LOGICAL_AND_EXPR_TAIL_AND_EQUALITY_EXPR_LOGICAL_AND_EXPR_TAIL,
  PROD_LOGICAL_AND_EXPR_TAIL_EPSILON,

  PROD_EQUALITY_EXPR_RELATIONAL_EXPR_EQUALITY_EXPR_TAIL,

  PROD_EQUALITY_EXPR_TAIL_EQUAL_RELATIONAL_EXPR_EQUALITY_EXPR_TAIL,
  PROD_EQUALITY_EXPR_TAIL_NOT_EQUAL_RELATIONAL_EXPR_EQUALITY_EXPR_TAIL,
  PROD_EQUALITY_EXPR_TAIL_EPSILON,

  PROD_RELATIONAL_EXPR_ADD_EXPR_RELATIONAL_EXPR_TAIL,

  PROD_RELATIONAL_EXPR_TAIL_LESS_ADD_EXPR_RELATIONAL_EXPR_TAIL,
  PROD_RELATIONAL_EXPR_TAIL_LESS_EQUAL_ADD_EXPR_RELATIONAL_EXPR_TAIL,
  PROD_RELATIONAL_EXPR_TAIL_GREATER_ADD_EXPR_RELATIONAL_EXPR_TAIL,
  PROD_RELATIONAL_EXPR_TAIL_GREATER_EQUAL_ADD_EXPR_RELATIONAL_EXPR_TAIL,
  PROD_RELATIONAL_EXPR_TAIL_EPSILON,

  PROD_ADD_EXPR_TERM_ADD_EXPR_TAIL,

  PROD_ADD_EXPR_TAIL_PLUS_TERM_ADD_EXPR_TAIL,
  PROD_ADD_EXPR_TAIL_MINUS_TERM_ADD_EXPR_TAIL,
  PROD_ADD_EXPR_TAIL_EPSILON,

  PROD_TERM_FACTOR_TERM_TAIL,

  PROD_TERM_TAIL_MULTIPLY_FACTOR_TERM_TAIL,
  PROD_TERM_TAIL_DIVIDE_FACTOR_TERM_TAIL,
  PROD_TERM_TAIL_EPSILON,

  PROD_FACTOR_IDENTIFIER,
  PROD_FACTOR_NUMBER,
  PROD_FACTOR_STRING_LITERAL,
  PROD_FACTOR_CHAR_LITERAL,
  PROD_FACTOR_LPAREN_EXPR_RPAREN,

  PROD_TYPE_INT,
  PROD_TYPE_FLOAT,
  PROD_TYPE_CHAR,
  PROD_TYPE_STRING

} Production;

Production ll1_lookup(GrammarSymbol non_terminal, GrammarSymbol lookahead);

#endif
